### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by PawarenessC** [FuckingCodeGenerator/MoneySystem#2]
2つ質問があります。
・MSUIとMoneySystemを別にしないのは何故ですか？
・コンソールに出るバックアップのログを出さないようにすることはできますか？

**Comment by FuckingCodeGenerator** [comment]
質問ありがとうございます。

> MSUIとMoneySystemを別にしないのは何故ですか？

_"別にしないのは何故ですか"_ これは「別にしたのは何故ですか」ということだと解釈します。

MoneySystemのユーザーの中には標準搭載のUIフォームが気に入っていない方や、独自の機能を搭載したいと考えている方がおり、そのユーザーはアップデートが来るたびにプラグインを書き直さなければならず、不便です。
そのため、APIとコントローラを分けることでサーバーごとの独自のUIフォームを別プラグインとして実装することができ、毎回書き直す負担が減ります。

> コンソールに出るバックアップのログを出さないようにすることはできますか？

現在はできません。
次回のアップデートで実装します。
ご意見ありがとうございます。

**Comment by PawarenessC** [comment]
ご回答ありがとうございます。
誤字失礼しました。
