### ISSUE TITLE
FallbackPrefixにプラグイン名を指定する

### ISSUE THREAD

**Issue by pmpldev** [FuckingCodeGenerator/MoneySystem#4]
コマンドのFallbackPrefixにプラグイン名を指定することを提案します。

現時点ではFallbackPrefixにコマンド名が指定されていますが、それをプラグイン名にすることによって、コマンドが重複した場合でも`/プラグイン名(FallbackPrefix):コマンド名`とすることで使用することが出来るようになります。
[参考(CommandMap.php)](https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/command/CommandMap.php#L35)

これは、実質的にPMMP公式も推奨している方法です。
[Poggit Rules Viewer](https://poggit.pmmp.io/rules.edit) C2aを参照

どうぞよろしくお願い致します。

**Comment by FuckingCodeGenerator** [comment]
issueありがとうございます。
修正しました。
